if(window.Raven){var ravenOptions={whitelistUrls:[/www\.zenius\.net/],ignoreErrors:"top.GLOBALS;originalCreateNotification;canvas.contentDocument;MyApp_RemoveAllHighlights;http://tt.epicplay.com;Can't find variable: ZiteReader;jigsaw is not defined;ComboSearch is not defined;http://loading.retry.widdit.com/;atomicFindClose;fb_xd_fragment;bmi_SafeAddOnload;EBCallBackMessageReceived;conduitPage;Script error.".split(";"),ignoreUrls:[/graph\.facebook\.com/i,/connect\.facebook\.net\/en_US\/all\.js/i,/eatdifferent\.com\.woopra-ns\.com/i,
/static\.woopra\.com\/js\/woopra\.js/i,/extensions\//i,/^chrome:\/\//i,/127\.0\.0\.1:4001\/isrunning/i,/webappstoolbarba\.texthelp\.com\//i,/metrics\.itunes\.apple\.com\.edgesuite\.net\//i,/cdn\.syndication\.twimg\.com/i]};Raven.config("https://a5e5098c07ce4231a6afd99a4e097a94@app.getsentry.com/12748",ravenOptions).install()}else window.Raven={captureException:function(a){throw a;}};
var jZnet=function(a,b,g,h){return a}(jZnet||{},jQuery,window),znet=function(a,b,g,h){return a}(znet||{},jQuery,window),znet=function(a,b,g,h){(a.sec=a.sec||{}).xsrfHeader=function(){var a={};a["X-"+b("meta[name='znet:xsrf-param']").attr("content")]=b("meta[name='znet:xsrf-token']").attr("content");return a};return a}(znet||{},jQuery,window);
jZnet.notification=function(a){var b={};a.prototype.options.styling="fontawesome";a.prototype.options.delay=3E3;b.ok=function(b){new a({title:"Success",text:b.join("<br>"),type:"success"})};b.error=function(b){new a({title:"Error",text:b.join("<br>"),type:"error"})};b.alert=function(b){new a({title:"Warning",text:b.join("<br>")})};return b}(PNotify);function moneyFormat(a){var b;for(b=Math.floor((a.length-1)/3);0<b;b--)a=a.substr(0,a.length-3*b)+"."+a.substr(a.length-3*b,3*b);return a}
znet=function(a,b,g,h){(a.homePage=a.homePage||{}).init=function(){b("#owl-demo").owlCarousel({items:4,lazyLoad:!0,navigation:!0});jQuery(".fullwidthbanner-container").hover(function(){jQuery(".tp-leftarrow").stop().animate({opacity:1},"easeIn");jQuery(".tp-rightarrow").stop().animate({opacity:1},"easeIn")},function(){jQuery(".tp-leftarrow").stop().animate({opacity:0},"easeIn");jQuery(".tp-rightarrow").stop().animate({opacity:0},"easeIn")});jQuery(".slider-wrapper").hover(function(){jQuery(".nivo-prevNav").stop().animate({opacity:1},
"easeIn");jQuery(".nivo-nextNav").stop().animate({opacity:1},"easeIn")},function(){jQuery(".nivo-prevNav").stop().animate({opacity:0},"easeIn");jQuery(".nivo-nextNav").stop().animate({opacity:0},"easeIn")});b("a[rel^='prettyPhoto']").prettyPhoto({animation_speed:"fast",slideshow:5E3,autoplay_slideshow:!1,opacity:.8,show_title:!0,allow_resize:!0,default_width:500,default_height:344,counter_separator_label:"/",theme:"pp_default",horizontal_padding:20,hideflash:!1,wmode:"opaque",autoplay:!0,modal:!1,
deeplinking:!0,overlay_gallery:!0,keyboard_shortcuts:!0,changepicturecallback:function(){},callback:function(){},ie6_fallback:!0,markup:'<div class="pp_pic_holder">                  <div class="ppt">&nbsp;</div>                  <div class="pp_top">                  <div class="pp_left"></div>                  <div class="pp_middle"></div>                  <div class="pp_right"></div>              </div>                  <div class="pp_content_container">                  <div class="pp_left">                  <div class="pp_right">                  <div class="pp_content">                  <div class="pp_loaderIcon"></div>                  <div class="pp_fade">                  <a href="#" class="pp_expand" title="Expand the image">Expand</a>                  <div class="pp_hoverContainer">                  <a class="pp_next" href="#">next</a>                  <a class="pp_previous" href="#">previous</a>              </div>                  <div id="pp_full_res"></div>                  <div class="pp_details">                  <div class="pp_nav">                  <a href="#" class="pp_arrow_previous">Previous</a>                  <p class="currentTextHolder">0/0</p>                  <a href="#" class="pp_arrow_next">Next</a>              </div>                  <p class="pp_description"></p>              {pp_social}                  <a class="pp_close" href="#">Close</a>              </div>              </div>              </div>              </div>              </div>              </div>                  <div class="pp_bottom">                  <div class="pp_left"></div>                  <div class="pp_middle"></div>                  <div class="pp_right"></div>              </div>              </div>                  <div class="pp_overlay"></div>',
gallery_markup:'<div class="pp_gallery"> <a href="#" class="pp_arrow_previous">Previous</a> <div> <ul> {gallery} </ul>  </div>   <a href="#" class="pp_arrow_next">Next</a> </div>',image_markup:'<img id="fullResImage" src="{path}" />',flash_markup:'<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="{width}" height="{height}"><param name="wmode" value="{wmode}" /><param name="allowfullscreen" value="true" /><param name="allowscriptaccess" value="always" /><param name="movie" value="{path}" /><embed src="{path}" type="application/x-shockwave-flash" allowfullscreen="true" allowscriptaccess="always" width="{width}" height="{height}" wmode="{wmode}"></embed></object>',
quicktime_markup:'<object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" height="{height}" width="{width}"><param name="src" value="{path}"><param name="autoplay" value="{autoplay}"><param name="type" value="video/quicktime"><embed src="{path}" height="{height}" width="{width}" autoplay="{autoplay}" type="video/quicktime" pluginspage="http://www.apple.com/quicktime/download/"></embed></object>',iframe_markup:'<iframe src ="{path}" width="{width}" height="{height}" frameborder="no"></iframe>',
inline_markup:'<div class="pp_inline">{content}</div>',custom_markup:"",social_tools:'<div class="pp_social"><div class="twitter"><a href="http://twitter.com/share" class="twitter-share-button" data-count="none">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js">\x3c/script></div><div class="facebook"><iframe src="http://www.facebook.com/plugins/like.php?locale=en_US&href='+location.href+'&amp;layout=button_count&amp;show_faces=true&amp;width=500&amp;action=like&amp;font&amp;colorscheme=light&amp;height=23" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:500px; height:23px;" allowTransparency="true"></iframe></div></div>'});
jQuery.fn.cssOriginal!=h&&(jQuery.fn.css=jQuery.fn.cssOriginal);jQuery(".fullwidthbanner").revolution({delay:9E3,startwidth:1170,startheight:470,onHoverStop:"on",thumbWidth:100,thumbHeight:50,thumbAmount:3,hideThumbs:0,navigationType:"none",navigationArrows:"solo",navigationStyle:"square",navigationHAlign:"center",navigationVAlign:"top",navigationHOffset:0,navigationVOffset:20,soloArrowLeftHalign:"left",soloArrowLeftValign:"center",soloArrowLeftHOffset:0,soloArrowLeftVOffset:0,soloArrowRightHalign:"right",
soloArrowRightValign:"center",soloArrowRightHOffset:0,soloArrowRightVOffset:0,touchenabled:"on",stopAtSlide:-1,stopAfterLoops:-1,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,hideSliderAtLimit:0,fullWidth:"on",shadow:0});jQuery(".client").parallax("50%",.1);jQuery(".service-reasons").parallax("50%",.1);jQuery("a[data-rel^='prettyPhoto']").prettyPhoto({overlay_gallery:!1})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h,k){function f(){b("#sourl").click(function(c){c.preventDefault();g(b.ajax({dataType:"json",url:"/sign-out",type:"POST",data:JSON.stringify({}),contentType:"application/json; charset=UTF-8",headers:a.sec.xsrfHeader()})).then(function(c){b.publish("znet.signedOut");h.location.reload()}).fail(function(c){b.publish("znet.signedOut");h.location.reload()})});var c=b("#userctrl");b.subscribe("znet.signedIn",function(e){b.data(c,"isSignedIn",!0)});b.subscribe("znet.notSignedIn",function(e){b.data(c,
"isSignedIn",!1)});b.subscribe("znet.signedOut",function(c){b("#silink").show();b("#sulink").show();b("#userctrl").hide()});b.subscribe("znet.hasSignedInFromAnotherBrowser",function(c){b("#silink").show();b("#sulink").show();b("#userctrl").hide()});b.subscribe("znet.memberPremiumInfoUpdate",function(c,d){b("#mbtp").text("Premium");b("#xpdt").text(d).show()})}function d(){b(".search-text-box").focus(function(){b("ul.social").animate({marginLeft:"10px"},450,"easeInSine")});b("#menu").slicknav({prependTo:"#mobilemenu"});
b(".slicknav_menu").prepend('<div id="search-form" class="visible-xs search-form-mobile pull-left"> <form action="#" method="get"> <input type="text" placeholder="Kode Konten" class="search-text-box"> </form> </div>');b("ul.sf-menu").stop().superfish({delay:50});b(".main-header").sticky({topSpacing:0});b(h).scroll(function(){100<b(this).scrollTop()?b(".scrollup").fadeIn():b(".scrollup").fadeOut()});b(".scrollup").click(function(){b("html, body").animate({scrollTop:0},600);return!1});b(".accordionMod").each(function(c){var d=
b(this).children(),a=c+1;b(this).attr("id","accordion"+a);d.each(function(c){c+=1;var d=b(this).parent().attr("id"),e=b(this).find(".accordion-toggle"),f=b(this).find(".accordion-inner");b(this).addClass("panel");f.wrap('<div id="collapseBox'+a+"_"+c+'" class="panel-collapse collapse" />');e.wrap('<div class="panel-heading" />');e.attr("data-toggle","collapse").attr("data-parent","#"+d).attr("data-target","#collapseBox"+a+"_"+c)});b(".accordion-toggle").prepend('<span class="icon" />');b("div.accordion-item:first-child .accordion-toggle").addClass("current");
b("div.accordion-item:first-child .icon").addClass("iconActive");b("div.accordion-item:first-child .panel-collapse").addClass("in");b(".accordionMod .accordion-toggle").click(function(){b(this).parent().parent().find(".panel-collapse").is(".in")?(b(this).removeClass("current"),b(this).find(".icon").removeClass("iconActive")):(b(this).addClass("current"),b(this).find(".icon").addClass("iconActive"));b(this).parent().parent().siblings().find(".accordion-toggle").removeClass("current");b(this).parent().parent().siblings().find(".accordion-toggle > .icon").removeClass("iconActive")})});
b(".accordion-toggle").removeClass("current");b(".accordion-toggle").addClass("collapsed");b(".panel-collapse").removeClass("in");b(".panel-collapse").addClass("collapse");b(".icon").removeClass("iconActive");var c=location.href.split("#")[1]||"";"membership"===c&&(c=3);b("#horizontal-tabs").tytabs({tabinit:c,fadespeed:"fast"})}(a.common=a.common||{}).init=function(){var c,e,a;b.cookies.test()||(c=["Please enable cookies in your browser's settings"],jZnet.notification.alert(c));c=[];a=b.cookies.filter(/^znet_msgok/);
for(e in a)a.hasOwnProperty(e)&&(c.push(a[e].replace(/\+/g," ")),b.cookies.del(e));1>c.length||jZnet.notification.ok(c);a=b.cookies.filter(/^znet_msgerr/);c=[];for(e in a)a.hasOwnProperty(e)&&(c.push(a[e].replace(/\+/g," ")),b.cookies.del(e));1>c.length||jZnet.notification.error(c);d();f()};return a}(znet||{},jQuery,Q,window);
znet=function(a,b,g,h){(a.signInPage=a.signInPage||{}).init=function(){b("#txtPasswordFake").keyup(function(){b("#txtPassword").val(b(this).val())});b("#show-passwd").change(function(){var a=b("#txtPassword"),d=b("#txtPasswordFake");b(this).prop("checked")?(d.val(a.val()),a.hide(),d.show()):(a.val(d.val()),a.show(),d.hide())});b("#fmLogin").validate({messages:{email:"",password:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,d,c){b(a).parents(".form-group").addClass(d).removeClass(c)},
unhighlight:function(a,d,c){b(a).parents(".form-group").removeClass(d).addClass(c)}});var a=b("#btnSubmit");a.click(function(f){f.preventDefault();b("#show-passwd").prop("checked",!1);b("#txtPassword").show();b("#txtPasswordFake").hide();b("#fmLoginMsg").hide();b("#fmLogin").valid()&&(a.html("Signing in ..."),Q(b.ajax({dataType:"json",url:"/sign-in",type:"POST",data:JSON.stringify({email:b("#txtEmail").attr("value"),password:b("#txtPassword").attr("value")}),contentType:"application/json; charset=utf-8",
headers:znet.sec.xsrfHeader()})).then(function(b){var c,a;try{if(a=purl(),c=a.param("retUrl"),c===h||null===c||""==c)throw Error();}catch(k){c=g.location.protocol+"//"+g.location.host}g.location.href=c}).fail(function(a){a=a.responseJSON;b("#fmLoginMsg").empty().append(a.msg.join(", "));b("#fmLoginMsg").show()}).done(function(){a.html("Sign in")}))})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){var k=a.UTIL=a.UTIL||{};k.fire=function(b,a,c){var e=znet;a=a===h?"init":a;if(""!==b&&e[b]&&"function"==typeof e[b][a])e[b][a](c)};k.loadEvents=function(){var a=document.body.id;k.fire("common");b.each(document.body.className.split(/\s+/),function(b,c){k.fire(c);k.fire(c,a)});k.fire("common","finalize")};return a}(znet||{},jQuery,window);$(document).ready(znet.UTIL.loadEvents);
znet=function(a,b,g,h){h=a.content=a.content||{};h.init_flash_html5_switch=function(){console.log("inited");b("#flashhtml5-switch").on("click",function(a){a=b(a.currentTarget);"FLASH"==a.data("player")?a.data("player","HTML5"):"HTML5"==a.data("player")&&a.data("player","FLASH");"FLASH"!=a.data("player")&&"HTML5"!=a.data("player")||Q(b.ajax({dataType:"json",type:"POST",url:"/visitor/setting/video-player",headers:znet.sec.xsrfHeader(),data:JSON.stringify({type:a.data("player")}),contentType:"application/json; charset=utf-8"})).then(function(b){g.location.reload()}).fail(function(b){}).done(function(b){})})};
h.init_ios_player_playlist=function(){var a,f=!1,d=b("#clip-data").data();b("ul.clips > li:first-child").addClass("c-active");a=b("#znet-player")[0];b("#znet-player");b.data(a,"video-id",d.videoId);b.data(a,"video-path",d.iosUrl);b(a).on("play",function(a){a=b(a.target).data("video-id");f=!0;ga("send","event","Videos","Play",a);b.ajax({dataType:"json",type:"POST",url:d.clickCountUrl,headers:znet.sec.xsrfHeader(),data:JSON.stringify({"video-id":a}),contentType:"application/json; charset=utf-8"})});
a.stop=function(){f=!1;this.pause();f=!0};b(a).on("pause",function(a){a=b(a.target).data("video-id");var e=this.currentTime;f?ga("send","event","Videos","Pause",a,e):ga("send","event","Videos","Stop",a,e)});b(a).on("ended",function(a){a=b(a.target).data("video-id");ga("send","event","Videos","Finish",a)});b("#vidlist").on("click","a",function(c){c.preventDefault();c.stopPropagation();b(".clips li.c-active").removeClass("c-active");b(c.target).parent().addClass("c-active");Q(b.ajax({dataType:"json",
url:c.target.href,headers:znet.sec.xsrfHeader()})).then(function(c){b("#znet-player-msg").empty();b("#znet-player-container").show();b.data(a,"video-id",c.clip.videoId);a.src=c.clip.iosUrl;a.play()}).fail(function(c){b("#znet-player-container").hide();403===c.status&&(a.stop(),"Premium only"===c.responseText?b("#znet-player-msg").html(b("#premium-only").html()).show():"Member only"===c.responseText&&b("#znet-player-msg").html(b("#member-only").html()).show())})});b("#znet-player-container").show()};
h.init_flash_player_playlist=function(){var a;b("#flash-data").data();b("#clip-data").data();b("#vidlist").on("click","a",function(f){f.preventDefault();f.stopPropagation();b(".clips li.c-active").removeClass("c-active");b(f.target).parent().addClass("c-active");f=f.target.href;a=$f(document.getElementById("znet-player"));Q(b.ajax({dataType:"json",url:f,headers:znet.sec.xsrfHeader()})).then(function(d){b("#znet-player-msg").empty();b("#znet-player-container").show();a.play(d.clip)}).fail(function(d){b("#znet-player-container").hide();
403===d.status&&(a.stop(),"Premium only"===d.responseText?b("#znet-player-msg").html(b("#premium-only").html()).show():"Member only"===d.responseText&&b("#znet-player-msg").html(b("#member-only").html()).show())})});b("#znet-player-container").show();b("ul.clips > li:first-child").addClass("c-active")};h.member_session_check=function(a){b.PeriodicalUpdater("/fe-api/0/content/member-session-check",{method:"POST",headers:znet.sec.xsrfHeader(),data:JSON.stringify({"content-page-sess-id":a}),contentType:"application/json; charset=utf-8",
dataType:"json",minTimeout:4E3,maxTimeout:6E4,multiplier:3,verbose:0,error:function(a,d,c){400===a.status&&b.publish("znet.signedOut")}},function(a,d,c,e){a=a.status;"not signed-in"===a&&(b.publish("znet.notSignedIn"),e.stop());"signed-in from another browser"==a&&(b.publish("znet.hasSignedInFromAnotherBrowser"),e.stop());"signed-in"==a&&b.publish("znet.signedIn");"signed-out"==a&&(b.publish("znet.signedOut"),e.stop())});b.subscribe("znet.signedOut",function(a){b("div.clips").empty();b("#contents").html(b("#has-signed-out").html())});
b.subscribe("znet.hasSignedInFromAnotherBrowser",function(a){b("div.clips").empty();b("#contents").html(b("#has-signed-in-from-another-browser").html())})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.contentPage=a.contentPage||{}).init=function(){if(b("#contents").data("is-mbr")){var k=b("#contents").data("content-page-sess-id");a.content.member_session_check(k)}b("#contents").data("is-flash")&&a.content.init_flash_player_playlist();b("#contents").data("is-ios")&&a.content.init_ios_player_playlist();a.content.init_flash_html5_switch()};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){function k(a,e){b(".znet-player").each(function(){this.stop()});var d=b("#znet-player-"+a)[0];Q(b.ajax({dataType:"json",url:e,headers:znet.sec.xsrfHeader()})).then(function(e){b.data(d,"video-id",e.clip.videoId);b("#im-item-video-player-container-"+a).show();d.src=e.clip.iosUrl;c("#im-item-label-"+a);d.play()}).fail(function(c){403===c.status&&(b("#im-item-video-player-container-"+a).empty(),"Premium only"===c.responseText?b("#im-item-video-player-container-"+a).html(b("#premium-only").html()).show():
"Member only"===c.responseText&&b("#im-item-video-player-container-"+a).html(b("#member-only").html()).show())})}function f(a,e){Q(b.ajax({dataType:"json",url:e,headers:znet.sec.xsrfHeader()})).then(function(e){b("#znet-player-"+a).attr("href",e.clip.url);var f;b(".znet-player").flowplayer().each(function(){d();this.getParent().id=="znet-player-"+a&&(f=this)});c("#im-item-label-"+a);b("#im-item-video-player-container-"+a).show();f.play(e.clip)}).fail(function(c){403===c.status&&(b("#im-item-video-player-container-"+
a).empty(),"Premium only"===c.responseText?b("#im-item-video-player-container-"+a).html(b("#premium-only").html()).show():"Member only"===c.responseText&&b("#im-item-video-player-container-"+a).html(b("#member-only").html()).show())})}function d(){b(".znet-player").flowplayer().each(function(){this.unload()})}var c=function(a){a=b(a);a.length&&(a=a.offset().top,b("html,body").animate({scrollTop:a},1E3));return!1},e=function(){var a=b("#flash-data").data(),c=b("#clip-data").data();flowplayer("a.znet-player",
{src:a.fpFlashParamSrc,wmode:"opaque",version:[10,1],onFail:function(){document.getElementById("info").innerHTML="You need the latest Flash version to view MP4 movies. Your version is "+this.getVersion()+" You can download here http://get.adobe.com/flashplayer/"}},{debug:!1,showErrors:!1,key:"#$0ef3073b1d40602b7d6",clip:{url:c.clipUrl,videoId:c.firstVideoId,netConnectionUrl:a.flashVideoUrl,scaling:a.scaling,provider:"rtmp",connectionProvider:"secure",onStart:function(a){ga("send","event","Videos",
"Play",a.videoId);b.ajax({dataType:"json",type:"POST",url:c.clickCountUrl,headers:znet.sec.xsrfHeader(),data:JSON.stringify({"video-id":a.videoId}),contentType:"application/json; charset=utf-8"})},onPause:function(b){ga("send","event","Videos","Pause",b.videoId,parseInt(this.getTime()))},onStop:function(b){ga("send","event","Videos","Stop",b.videoId,parseInt(this.getTime()))},onFinish:function(b){ga("send","event","Videos","Finish",b.videoId,parseInt(this.getTime()))}},logo:{opacity:.2,fullscreenOnly:!1,
displayTime:5,fadeSpeed:1E3,url:a.pluginLogoUrl},plugins:{controls:{url:a.pluginControlsUrl},rtmp:{url:a.pluginRtmpUrl,proxyType:a.pluginRtmpProxyType},secure:{url:a.pluginSecureUrl+a.pluginSecureKey}}})},l=function(){var a=b(".znet-player"),c=b("#clip-data").data();a.data("ios-player-pause-event",!1);a.on("play",function(a){a=b(a.target).data("video-id");ga("send","event","Videos","Play",a);b.ajax({dataType:"json",type:"POST",url:c.clickCountUrl,headers:znet.sec.xsrfHeader(),data:JSON.stringify({"video-id":a}),
contentType:"application/json; charset=utf-8"})});a.each(function(){this.stop=function(){b(this).data("ios-player-pause-event",!1);this.pause();b(this).data("ios-player-pause-event",!0)}});a.on("pause",function(a){a=b(a.target).data("video-id");var c=this.currentTime;b(this).data("ios-player-pause-event")?ga("send","event","Videos","Pause",a,c):ga("send","event","Videos","Stop",a,c)});a.on("ended",function(a){a=b(a.target).data("video-id");ga("send","event","Videos","Finish",a)})};(a.contentInteractiveModulePage=
a.contentInteractiveModulePage||{}).init=function(){b(".widget ul.tabs li").click(function(){d()});b("#interactive-module-items").data("is-flash")&&e();b("#interactive-module-items").data("is-ios")&&l();b.subscribe("/j-znet/interactive-module/show-video-btn/clicked",function(a,c){d();b(".show-video-btn").show();b(".show-image-btn").hide();b("#show-video-btn-"+c).hide();b("#show-image-btn-"+c).show();b(".im-item-image-container").show();b("#im-item-image-container-"+c).hide();b(".im-item-image-container-toolbar").show();
b("#im-item-image-container-toolbar-"+c).hide();b(".im-item-video-player-container").hide();b("#im-item-video-player-toolbar-"+c).show();var e=b("#im-item-video-endpoint-"+c).attr("href");b("#interactive-module-items").data("is-flash")&&f(c,e);b("#interactive-module-items").data("is-ios")&&k(c,e)});b.subscribe("/j-znet/interactive-module/show-image-btn/clicked",function(a,e){b(".show-video-btn").show();b(".show-image-btn").hide();b("#show-video-btn-"+e).show();b("#show-image-btn-"+e).hide();b("#im-item-image-container-"+
e).show();b(".im-item-video-player-toolbar").hide();b("#im-item-image-container-toolbar-"+e).show();b(".im-item-video-player-container").hide();c("#im-item-label-"+e)});b("#interactive-module-items").on("click",".show-video-btn",function(a){a.stopPropagation();a.preventDefault();a=b(a.target);a=parseInt(a.attr("id").replace("show-video-btn-",""),10);b.publish("/j-znet/interactive-module/show-video-btn/clicked",[a])});b("#interactive-module-items").on("click",".show-image-btn",function(a){a.stopPropagation();
a.preventDefault();a=b(a.target);a=parseInt(a.attr("id").replace("show-image-btn-",""),10);b.publish("/j-znet/interactive-module/show-image-btn/clicked",[a])});b("#interactive-module-items").on("click",".reload-video-btn",function(a){a.stopPropagation();a.preventDefault();a=b(a.target);a=parseInt(a.attr("id").replace("reload-video-btn-",""),10);b("#im-item-video-player-container-"+a).empty();b.publish("/j-znet/interactive-module/show-video-btn/clicked",[a]);return!1});b("table#interactive-module-items").on("click",
".reload-regular-image-btn",function(a){a.preventDefault();a.stopPropagation();a=b(a.target).parent();a=parseInt(a.attr("id").replace("im-item-image-container-toolbar-",""),10);a=b("#im-item-image-container-"+a).children("img");var c=a.attr("src");a.removeAttr("src");a.attr("src",c)})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){function k(){var a=b("#flash-data").data(),c=b("#clip-data").data();b("a#znet-player").css({margin:"0 auto",display:"block",height:g.innerHeight-40,width:g.innerWidth-40});flowplayer("znet-player",{src:a.fpFlashParamSrc,wmode:"opaque",version:[10,1],onFail:function(){document.getElementById("info").innerHTML="You need the latest Flash version to view MP4 movies. Your version is "+this.getVersion()+" You can download here http://get.adobe.com/flashplayer/"}},{debug:!1,showErrors:!1,
key:"#$0ef3073b1d40602b7d6",clip:{url:c.clipUrl,videoId:c.firstVideoId,netConnectionUrl:a.flashVideoUrl,scaling:a.scaling,provider:"rtmp",connectionProvider:"secure",onStart:function(b){ga("send","event","Videos","Play",b.videoId)},onPause:function(b){ga("send","event","Videos","Pause",b.videoId,parseInt(this.getTime()))},onStop:function(b){ga("send","event","Videos","Stop",b.videoId,parseInt(this.getTime()))},onFinish:function(b){ga("send","event","Videos","Finish",b.videoId,parseInt(this.getTime()))}},
logo:{top:130,right:232,opacity:.2,fullscreenOnly:!1,displayTime:5,fadeSpeed:1E3,url:a.pluginLogoUrl},plugins:{controls:{url:a.pluginControlsUrl},rtmp:{url:a.pluginRtmpUrl,proxyType:a.pluginRtmpProxyType},secure:{url:a.pluginSecureUrl+a.pluginSecureKey}},onError:function(b,a){}})}function f(){b("video#znet-player").attr({height:g.innerHeight-40,width:g.innerWidth-40});var a=b("#znet-player"),c=a[0],e=!1,f=b("#clip-data").data();b.data(c,"video-id",f.videoId);b.data(c,"video-path",f.iosUrl);a.on("play",
function(a){a=b(a.target).data("video-id");e=!0;ga("send","event","Videos","Play",a)});c.stop=function(){e=!1;this.pause();e=!0};a.on("pause",function(a){a=b(a.target).data("video-id");var c=this.currentTime;e?ga("send","event","Videos","Pause",a,c):ga("send","event","Videos","Stop",a,c)});a.on("ended",function(a){a=b(a.target).data("video-id");ga("send","event","Videos","Finish",a)})}(a.videoEmbedPage=a.videoEmbedPage||{}).init=function(){var a=b("#znet-player-container");a.data("is-flash")&&k();
a.data("is-ios")&&f()};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.tryoutAnswerPage=a.tryoutAnswerPage||{}).init=function(){b("button[rel]").overlay({effect:"apple",expose:"#789",onLoad:function(a){a=this.getOverlay();var f=parseInt(a.children(".to-content-id").html(),10),d=parseInt(a.children(".to-playlist-id").html(),10),c=parseInt(a.children(".to-item-id").html(),10);b('<iframe height="432" width="576" src="/c/'+f+"/playlist/"+d+"/item/"+c+'/embed" frameborder="0"></iframe>').appendTo(a)},onClose:function(b){this.getOverlay().children("iframe").remove()}})};
return a}(znet||{},jQuery,window);znet=function(a,b,g,h){(a.tryoutPage=a.tryoutPage||{}).init=function(){function a(f,d){var c=b("input:radio").serialize(),e=b("#to-data").data("to-id");b.post("/tryout/2/answer/temp","toid="+e+"&"+c,function(b){})}b("input:radio").bind("click mousedown",function(){var b;return function(d){"click"==d.type?(b?(b=this.checked=!1,this.value=""):b=!0,a(this.name,this.value)):b=this.checked}}())};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){function k(){var a=b("#clip-data").data();flowplayer.conf={analytics:"UA-26417230-1",ratio:.75,autoplay:!0};b("#znet-player-container0").flowplayer({debug:!1,splash:!0,playlist:[[{mp4:a.iosUrl},{mpegurl:a.iosUrl}]]});var e=b("#znet-player-container0")[0];b.data(e,"video-id",a.videoId);flowplayer(function(e,d){e.bind("play",function(e){e=b(e.target).data("video-id");ga("send","event","Videos","Play",e);b.ajax({dataType:"json",type:"POST",url:a.videoClickCountUrl,headers:znet.sec.xsrfHeader(),
data:JSON.stringify({"video-id":e}),contentType:"application/json; charset=utf-8"})});e.bind("stop",function(a){a=b(a.target).data("video-id");ga("send","event","Videos","Stop",a,this.currentTime)});e.bind("pause",function(a){a=b(a.target).data("video-id");ga("send","event","Videos","Pause",a,this.currentTime)});e.bind("finish",function(a){a=b(a.target).data("video-id");ga("send","event","Videos","Finish",a)});return e});var d=flowplayer("#znet-player-container0");b("#vidlist").on("click","a",function(a){b("#znet-player-container0").show();
a.preventDefault();a.stopPropagation();b(".clips li.c-active").removeClass("c-active");b(a.target).parent().addClass("c-active");Q(b.ajax({dataType:"json",url:a.target.href,headers:znet.sec.xsrfHeader()})).then(function(a){b("#znet-player-msg").empty();b.data(e,"video-id",a.clip.videoId);d.ready?d.load([{mp4:a.clip.iosUrl},{mpegurl:a.clip.iosUrl}]):b("#znet-player-container0").flowplayer({debug:!1,splash:!0,playlist:[[{mp4:a.clip.iosUrl},{mpegurl:a.clip.iosUrl}]]})}).fail(function(a){b("#znet-player-container0").hide();
403===a.status&&(d.stop(),"Premium only"===a.responseText?b("#znet-player-msg").html(b("#premium-only").html()).show():"Member only"===a.responseText&&b("#znet-player-msg").html(b("#member-only").html()).show())})});b("#znet-player-container").show();b("ul.clips > li:first-child").addClass("c-active")}function f(a,e){var f=b("#znet-player-"+a);flowplayer.conf={analytics:"UA-26417230-1",ratio:.75,autoplay:!0};var k=f[0];Q(b.ajax({dataType:"json",url:e,headers:znet.sec.xsrfHeader()})).then(function(e){b.data(k,
"video-id",e.clip.videoId);f.flowplayer({debug:!1,splash:!0,playlist:[[{mp4:e.clip.iosUrl},{mpegurl:e.clip.iosUrl}]]});var g=flowplayer("#znet-player-"+a);g.ready?g.load([{mp4:e.clip.iosUrl},{mpegurl:e.clip.iosUrl}]):f.flowplayer({debug:!1,splash:!0,playlist:[[{mp4:e.clip.iosUrl},{mpegurl:e.clip.iosUrl}]]});b("#im-item-video-player-container-"+a).show();d("#im-item-label-"+a)}).fail(function(e){var d=flowplayer("#znet-player-"+a);403===e.status&&("undefined"!==typeof d&&d.stop(),b("#im-item-video-player-container-"+
a).empty(),"Premium only"===e.responseText?b("#im-item-video-player-container-"+a).html(b("#premium-only").html()).show():"Member only"===e.responseText&&b("#im-item-video-player-container-"+a).html(b("#member-only").html()).show())})}var d=function(a){a=b(a);a.length&&(a=a.offset().top,b("html,body").animate({scrollTop:a},1E3));return!1};(a.contentFp5Page=a.contentFp5Page||{}).init=function(){if(b("#contents").data("is-mbr")){var a=b("#contents").data("content-page-sess-id");znet.content.member_session_check(a)}k();
b.subscribe("/j-znet/interactive-module/show-video-btn/clicked",function(a,c){b(".show-video-btn").show();b(".show-image-btn").hide();b("#show-video-btn-"+c).hide();b("#show-image-btn-"+c).show();b(".im-item-image-container").show();b("#im-item-image-container-"+c).hide();b(".im-item-image-container-toolbar").show();b("#im-item-image-container-toolbar-"+c).hide();b(".im-item-video-player-container").hide();b("#im-item-video-player-toolbar-"+c).show();var d=b("#im-item-video-endpoint-"+c).attr("href");
f(c,d)});b.subscribe("/j-znet/interactive-module/show-image-btn/clicked",function(a,c){b(".show-video-btn").show();b(".show-image-btn").hide();b("#show-video-btn-"+c).show();b("#show-image-btn-"+c).hide();b("#im-item-image-container-"+c).show();b(".im-item-video-player-toolbar").hide();b("#im-item-image-container-toolbar-"+c).show();b(".im-item-video-player-container").hide();d("#im-item-label-"+c)});b("#interactive-module-items").on("click",".show-video-btn",function(a){a.stopPropagation();a.preventDefault();
a=b(a.target);a=parseInt(a.attr("id").replace("show-video-btn-",""),10);b.publish("/j-znet/interactive-module/show-video-btn/clicked",[a])});b("#interactive-module-items").on("click",".show-image-btn",function(a){a.stopPropagation();a.preventDefault();a=b(a.target);a=parseInt(a.attr("id").replace("show-image-btn-",""),10);b.publish("/j-znet/interactive-module/show-image-btn/clicked",[a])});b("#interactive-module-items").on("click",".reload-video-btn",function(a){a.stopPropagation();a.preventDefault();
a=b(a.target);a=parseInt(a.attr("id").replace("reload-video-btn-",""),10);b("#im-item-video-player-container-"+a).empty();b.publish("/j-znet/interactive-module/show-video-btn/clicked",[a]);return!1});b("table#interactive-module-items").on("click",".reload-regular-image-btn",function(a){a.preventDefault();a.stopPropagation();a=b(a.target).parent();a=parseInt(a.attr("id").replace("im-item-image-container-toolbar-",""),10);a=b("#im-item-image-container-"+a).children("img");var c=a.attr("src");a.removeAttr("src");
a.attr("src",c)})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.changePasswordPage=a.changePasswordPage||{}).init=function(){var a=b("#password"),f=b("#fakePassword"),d=b("#password_again"),c=b("#fakePasswordAgain");f.keyup(function(){a.val(b(this).val())});c.keyup(function(){d.val(b(this).val())});b("#show-passwd").change(function(){this.checked?(f.val(a.val()),a.hide(),f.show(),c.val(d.val()),d.hide(),c.show()):(a.val(f.val()),a.show(),f.hide(),d.val(c.val()),d.show(),c.hide())});var e=b("#changePasswordForm");e.validate({rules:{password:{required:!0,
minlength:5,maxlength:32},password_again:{equalTo:"#password"}},messages:{password:"",password_again:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,c,d){b(a).parents(".form-group").addClass(c).removeClass(d)},unhighlight:function(a,c,d){b(a).parents(".form-group").removeClass(c).addClass(d)},errorElement:"span"});var g=b("#changePasswordBtn");g.click(function(h){a.show();f.hide();d.show();c.hide();b("#show-passwd").prop("checked",!1);b("p.alert").remove();h.preventDefault();
e.valid()&&(g.text("Processing.."),e.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",url:"/change-password",type:"POST",data:JSON.stringify({password:b("#password").attr("value"),key:b("#changePasswordKey").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){e.find(":input:disabled").prop("disabled",!1);g.text("Change Password");b(".changePasswordSuccess").show();b(".changePasswordEl").hide()}).fail(function(a){e.find(":input:disabled").prop("disabled",
!1);g.text("Change Password");a=a.responseJSON;for(var c=0,c=0;c<a["err-msg"].length;c++)e.before(b("<p/>").attr("class","alert alert-danger").text(a["err-msg"][c]))}))})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.forgetPasswordPage=a.forgetPasswordPage||{}).init=function(){var a=b("#resetPasswordForm");a.validate({messages:{forgotmail:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,c,e){b(a).parents(".form-group").addClass(c).removeClass(e)},unhighlight:function(a,c,e){b(a).parents(".form-group").removeClass(c).addClass(e)},errorElement:"span"});var f=b("#forgotBtn");f.click(function(d){b("p.alert").remove();d.preventDefault();a.valid()&&(f.text("Processing.."),
a.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",url:"/forget-password",type:"POST",data:JSON.stringify({email:b("#forgotmail").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(c){c=c["succ-msgs"];var d=0;a.find(":input:disabled").prop("disabled",!1);f.text("Submit");for(d=0;d<c.length;d++)a.before(b("<p/>").attr("class","alert alert-success").text(c[d]))}).fail(function(c){a.find(":input:disabled").prop("disabled",
!1);f.text("Submit");c=c.responseJSON;for(var d=0,d=0;d<c["err-msgs"].length;d++)a.before(b("<p/>").attr("class","alert alert-danger").text(c["err-msgs"][d]))}))})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.signUpPage=a.signUpPage||{}).init=function(){var a=b("#mpassword"),f=b("#mpassword-fake"),d=b("#mvpassword"),c=b("#mvpassword-fake"),e=b("#signupform");e.validate({errorLabelContainer:"#messageBox",wrapper:"p",rules:{mname:{required:!0,minlength:3},mpassword:{required:!0,minlength:5,maxlength:32},mvpassword:{equalTo:"#mpassword"},mvemail:{equalTo:"#memail"}},messages:{mname:{required:"Mohon isi Full Name",minlength:"Full Name minimal 3 huruf/angka"},memail:{required:"Mohon isi Email"},
mvemail:{required:"Mohon isi Retype Email",equalTo:"Mohon Pastikan Email yang Anda ketik sama"},mpassword:{required:"Mohon isi Password",minlength:"Password minimal 5 huruf/angka"},mvpassword:{required:"Mohon isi Retype Password",equalTo:"Mohon Pastikan Password yang Anda ketik sama"}},errorClass:"has-error",validClass:"has-success",highlight:function(a,c,d){b(a).parents(".form-group").addClass(c).removeClass(d)},unhighlight:function(a,c,d){b(a).parents(".form-group").removeClass(c).addClass(d)}});
b("#mpassword-fake").keyup(function(){b("#mpassword").val(b(this).val())});b("#mvpassword-fake").keyup(function(){b("#mvpassword").val(b(this).val())});b("#show-passwd").change(function(){this.checked?(f.val(a.val()),a.hide(),f.show(),c.val(d.val()),d.hide(),c.show()):(a.val(f.val()),a.show(),f.hide(),d.val(c.val()),d.show(),c.hide())});var g=b("#signUpBtn");g.click(function(h){b("div.alert").empty().hide();b("div.success").empty().hide();h.preventDefault();a.show();f.hide();d.show();c.hide();b("#show-passwd").prop("checked",
!1);e.valid()&&(g.text("Processing.."),e.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",url:"/sign-up",type:"POST",data:JSON.stringify({mname:b("#mname").attr("value"),memail:b("#memail").attr("value"),mvemail:b("#mvemail").attr("value"),mpassword:b("#mpassword").attr("value"),mvpassword:b("#mvpassword").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){b(".signUpSucceeds").show();b(".signUpEl").hide();b("html, body").animate({scrollTop:b("#signUpSucceeds").offset().top},
1E3);ga("send","event","sign-up","click sign-up and get thank you notes")}).fail(function(a){a=a.responseJSON;for(var c=0,c=0;c<a["err-msgs"].length;c++)e.before(b("<p/>").attr("class","alert").text(a["err-msgs"][c]))}).done(function(){g.text("Sign Up");e.find(":input:disabled").prop("disabled",!1)}))})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){function k(){var a=b("#sendEmailChangeEmailBtn");a.click(function(c){c.preventDefault();a.attr("disabled","disabled").text("Sending...").prepend('<i class="fa fa-spinner fa-spin"></i> ');b("#emailVerMsg").empty();Q(b.ajax({dataType:"json",url:"/member/send-email-change-verification-email",type:"POST",data:JSON.stringify({}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){a=a["succ-msgs"];b("#chgEmailMsg").append(b("<p/>").attr("class",
"alert alert-success").text(a[0]))}).fail(function(a){a=a.responseJSON;b("#chgEmailMsg").append(b("<p/>").attr("class","alert alert-danger").text(a["err-msgs"][0]))}).done(function(){a.removeAttr("disabled").text("Kirim email untuk ubah email")})})}function f(){var a=b("#sendNewEmailVerificationEmailBtn"),c=b("#NewEmailMsg");a.click(function(d){d.preventDefault();0===b("#new-email").attr("value").length?c.append(b("<p/>").attr("class","alert alert-danger").text("please fill your email")):(a.attr("disabled",
"disabled").text("Sending...").prepend('<i class="fa fa-spinner fa-spin"></i> '),c.empty(),Q(b.ajax({dataType:"json",url:"/member/change-email-for-unverified-email",type:"POST",data:JSON.stringify({"new-email":b("#new-email").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){a=a["succ-msgs"];c.append(b("<p/>").attr("class","alert alert-success").text(a[0]))}).fail(function(a){a=a.responseJSON;c.append(b("<p/>").attr("class","alert alert-danger").text(a["err-msgs"][0]))}).done(function(){a.removeAttr("disabled").text("Kirim email verifikasi untuk email baru")}))})}
function d(){var a=b("#sendMemberVerificationEmailBtn");a.click(function(c){c.preventDefault();a.text("Sending...");b("#emailVerMsg").empty();Q(b.ajax({dataType:"json",url:"/member/send-verification-email",type:"POST",data:JSON.stringify({}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){a=a["succ-msgs"];b("#emailVerMsg").append(b("<p/>").attr("class","alert alert-success").text(a[0]))}).fail(function(a){a=a.responseJSON;b("#emailVerMsg").append(b("<p/>").attr("class",
"alert alert-danger").text(a["err-msgs"][0]))}).done(function(){a.text("Kirim email verifikasi")})})}function c(){var a=b("#mpassword"),c=b("#mpassword-fake"),d=b("#mvpassword"),e=b("#mvpassword-fake"),f=b("#signupform");f.validate({errorLabelContainer:"#messageBox",wrapper:"li",rules:{mpassword:{required:!0,minlength:5,maxlength:32},mvpassword:{equalTo:"#mpassword"},mvemail:{equalTo:"#memail"}},messages:{memail:{required:"Mohon isi Email"},mvemail:{required:"Mohon isi Retype Email",equalTo:"Mohon Pastikan Email yang Anda ketik sama"},
mpassword:{required:"Mohon isi Password",minlength:"Password minimal 5 huruf/angka"},mvpassword:{required:"Mohon isi Retype Password",equalTo:"Mohon Pastikan Password yang Anda ketik sama"}},errorClass:"invalidInputEl",validClass:"validInputEl"});b("#mpassword-fake").keyup(function(){b("#mpassword").val(b(this).val())});b("#mvpassword-fake").keyup(function(){b("#mvpassword").val(b(this).val())});b("#show-passwd").change(function(){this.checked?(c.val(a.val()),a.hide(),c.show(),e.val(d.val()),d.hide(),
e.show()):(a.val(c.val()),a.show(),c.hide(),d.val(e.val()),d.show(),e.hide())});var g=b("#signUpBtn");g.click(function(h){b("p.alert").empty().hide();h.preventDefault();a.show();c.hide();d.show();e.hide();b("#show-passwd").prop("checked",!1);f.valid()&&(g.text("Processing.."),f.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",url:"/member/email-based-account",type:"POST",data:JSON.stringify({mname:b("#mname").attr("value"),memail:b("#memail").attr("value"),mvemail:b("#mvemail").attr("value"),
mpassword:b("#mpassword").attr("value"),mvpassword:b("#mvpassword").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){b("#signUpSucceeds").append(b("#memail").attr("value"));b(".signUpSucceeds").show();b(".signUpEl").hide()}).fail(function(a){a=a.responseJSON;for(var c=0,c=0;c<a["err-msgs"].length;c++)f.before(b("<p/>").attr("class","alert alert-danger").text(a["err-msgs"][c]))}).done(function(){g.text("Create zenius.net account");f.find(":input:disabled").prop("disabled",
!1)}))})}function e(){var a=b("#sendPasswordChangeEmailBtn");a.click(function(c){c.preventDefault();a.text("Sending...");var d=b("#chgPwdMsg");d.empty();Q(b.ajax({dataType:"json",url:"/member/send-change-password-email",type:"POST",data:JSON.stringify({}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){a=a["succ-msgs"];d.append(b("<p/>").attr("class","alert alert-success").text(a[0]))}).fail(function(a){a=a.responseJSON;d.append(b("<p/>").attr("class",
"alert alert-danger").text(a["err-msgs"][0]))}).done(function(){a.text("Kirim email untuk ubah password")})})}(a.memberProfilePage=a.memberProfilePage||{}).init=function(){b("#sendEmailChangeEmailBtn").length&&k();b("#sendNewEmailVerificationEmailBtn").length&&f();b("#sendMemberVerificationEmailBtn").length&&d();b("#signupform").length&&c();b("#sendPasswordChangeEmailBtn").length&&e();a.content.init_flash_html5_switch()};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.studentPromoterSignUpPage=a.studentPromoterSignUpPage||{}).init=function(){var a=b("#srsignupform");a.validate({messages:{phone:"",school:"",grade:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,c,e){b(a).parents(".form-group").addClass(c).removeClass(e)},unhighlight:function(a,c,e){b(a).parents(".form-group").removeClass(c).addClass(e)},errorElement:"span"});var f=b("#suf_submit");f.click(function(d){d.preventDefault();a.valid()&&(f.attr("value",
"Processing..."),Q(b.ajax({dataType:"json",url:"/student-promoter-registration",type:"POST",data:JSON.stringify({phone:b("#phone").attr("value"),school:b("#school").attr("value"),grade:b("#grade").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){b("#su_form_cont").hide();b("#stdp_reg_success").show()}).fail(function(a){a=a.responseJSON;b("#regMsg").empty().append(a.msg.join(", "));b("#regMsg").show()}).done(function(){f.attr("value","Daftar Sekarang")}))})};
return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.voucherActivationPage=a.voucherActivationPage||{}).init=function(){b("#vactivate").validate({messages:{vcode:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,f,d){b(a).parents(".form-group").addClass(f).removeClass(d)},unhighlight:function(a,f,d){b(a).parents(".form-group").removeClass(f).addClass(d)},errorElement:"span"});b("#activateBtn").click(function(a){b("div.alert").remove();a.preventDefault();b("#vactivate").valid()&&(b("#activateBtn").attr("value",
"Processing.."),b("#vactivate").find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",url:"/voucher-activate",type:"POST",data:JSON.stringify({vcode:b("#vcode").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){b("#vactivate").find(":input:disabled").prop("disabled",!1);b("#activateBtn").attr("value","Submit");for(var d=0,d=0;d<a["succ-msgs"].length;d++)b("#vactivate").before(b("<div/>").attr("class","alert alert-success").text(a["succ-msgs"][d]));
b.publish("znet.memberPremiumInfoUpdate",[a.mbrExpDate])}).fail(function(a){a=a.responseJSON;for(var d=0,d=0;d<a["err-msgs"].length;d++)b("#vactivate").before(b("<div/>").attr("class","alert alert-danger").text(a["err-msgs"][d]));b("#vactivate").find(":input:disabled").prop("disabled",!1);b("#activateBtn").attr("value","Submit")}))})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.voucherXpediaActivationPage=a.voucherXpediaActivationPage||{}).init=function(){var a=b("#vXpediaActivate");a.validate({messages:{vcode:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,d,c){b(a).parents(".form-group").addClass(d).removeClass(c)},unhighlight:function(a,d,c){b(a).parents(".form-group").removeClass(d).addClass(c)},errorElement:"span"});b("#activateBtn").click(function(f){b("div.alert").remove();f.preventDefault();-1==="kelas 1;kelas 2;kelas 3;kelas 4;kelas 5;kelas 6".split(";").indexOf(b("#grade").attr("value"))?
b("#vzclubcode").rules("add",{required:!0}):(b("#vzclubcode").rules("remove"),a.children(".has-error").removeClass("has-error"));a.valid()&&(b("#activateBtn").html('<i class="fa fa-spinner fa-spin"></i> Activating...'),a.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",type:"POST",data:JSON.stringify({vznetcode:b("#vznetcode").attr("value"),vzclubcode:b("#vzclubcode").attr("value"),grade:b("#grade").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(d){a.find(":input:disabled").prop("disabled",
!1);b("#activateBtn").attr("value","Submit");var c=b("#xpediaSuccessMessage").clone();c.find("#expDate").text(d["znet-expiry-date"]);d["zclub-activation"]&&(b.isEmptyObject(d.zclub)?c.find(".zclubFailed").show():d.zclub["already-member"]?c.find(".zclub-already-member").show():(c.find(".clubUsername").text(d.zclub.username),c.find("#clubPassword").text(d.zclub.password),c.find(".zclub").show()));a.before(b("<div/>").attr("class","alert alert-success").html(c.html()));a.hide();b.publish("znet.memberPremiumInfoUpdate",
[d["znet-expiry-date"]])}).fail(function(d){d=d.responseJSON;if(null!==d&&"err-msgs"in d)for(var c=0,c=0;c<d["err-msgs"].length;c++)a.before(b("<div/>").attr("class","alert alert-danger").text(d["err-msgs"][c]));else a.before(b("<div/>").attr("class","alert alert-danger").text("Please try again"));a.find(":input:disabled").prop("disabled",!1);b("#activateBtn").text("Submit")}))})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.voucherIndischoolActivationPage=a.voucherIndischoolActivationPage||{}).init=function(){var a=b("#vIndischoolActivate");a.validate({messages:{vcode:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,d,c){b(a).parents(".form-group").addClass(d).removeClass(c)},unhighlight:function(a,d,c){b(a).parents(".form-group").removeClass(d).addClass(c)},errorElement:"span"});b("#activateBtn").click(function(f){b("div.alert").remove();f.preventDefault();a.valid()&&
(b("#activateBtn").html('<i class="fa fa-spinner fa-spin"></i> Activating...'),a.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",type:"POST",data:JSON.stringify({vznetcode:b("#vznetcode").attr("value"),grade:b("#grade").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(d){a.find(":input:disabled").prop("disabled",!1);b("#activateBtn").attr("value","Submit");var c=b("#indischoolSuccessMessage").clone();c.find("#expDate").text(d["znet-expiry-date"]);
c.find("#gradeExpDate").text(d.grade);a.before(b("<div/>").attr("class","alert alert-success").html(c.html()));a.hide();b.publish("znet.memberPremiumInfoUpdate",[d["znet-expiry-date"]])}).fail(function(d){d=d.responseJSON;if(null!==d&&"err-msgs"in d)for(var c=0,c=0;c<d["err-msgs"].length;c++)a.before(b("<div/>").attr("class","alert alert-danger").text(d["err-msgs"][c]));else a.before(b("<div/>").attr("class","alert alert-danger").text("Please try again"));a.find(":input:disabled").prop("disabled",
!1);b("#activateBtn").text("Submit")}))})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.changeEmailPage=a.changeEmailPage||{}).init=function(){b("#email");b("#email_again");var a=b("#changeEmailForm");a.validate({rules:{email:{required:!0,minlength:5,maxlength:32},email_again:{equalTo:"#email"}},messages:{email:"",email_again:""},errorClass:"has-error",validClass:"has-success",highlight:function(a,c,e){b(a).parents(".form-group").addClass(c).removeClass(e)},unhighlight:function(a,c,e){b(a).parents(".form-group").removeClass(c).addClass(e)},errorElement:"span"});
var f=b("#changeEmailBtn");f.click(function(d){b("p.alert").remove();d.preventDefault();a.valid()&&(f.text("Processing.."),a.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",type:"POST",data:JSON.stringify({email:b("#email").attr("value"),key:b("#changeEmailKey").attr("value")}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(c){a.find(":input:disabled").prop("disabled",!1);f.text("Change Email");b(".changeEmailSuccess").show();
b(".changeEmailEl").hide()}).fail(function(c){a.find(":input:disabled").prop("disabled",!1);f.text("Change Email");c=c.responseJSON;for(var d=0,d=0;d<c["err-msgs"].length;d++)a.before(b("<p/>").attr("class","alert alert-danger").text(c["err-msgs"][d]))}))})};return a}(znet||{},jQuery,window);znet=function(a,b,g,h){(a.invoicePage=a.invoicePage||{}).init=function(){};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.invoicePaymentConfirmationPage=a.invoicePaymentConfirmationPage||{}).init=function(){b("#tanggal").datetimepicker({pickTime:!1,language:"id"});var a=b("#confForm");a.validate({errorLabelContainer:"#messageBox",wrapper:"p",messages:{penyetor:{required:"Mohon isi nama pemilik rekening"},pengirim:{required:"Mohon isi nama bank asal"},mediabayar:{required:"Mohon pilih media pembayaran"},tanggal:{required:"Mohon isi tanggal transaksi"},amount:{required:"Mohon isi jumlah uang"},
bankzenius:{required:"Mohon isi rekening tujuan"}},errorClass:"has-error",validClass:"has-success",highlight:function(a,c,e){b(a).parents(".form-group").addClass(c).removeClass(e)},unhighlight:function(a,c,e){b(a).parents(".form-group").removeClass(c).addClass(e)}});var f=b("#confFormSubmit");f.click(function(d){d.preventDefault();b("#messageBox").empty().hide();a.valid()?(f.attr("value","Processing.."),a.find(":input:not(:disabled)").prop("disabled",!0),Q(b.ajax({dataType:"json",type:"POST",data:JSON.stringify({penyetor:b("#cpenyetor").attr("value"),
pengirim:b("#cpengirim").attr("value"),noreferensi:b("#cnoref").attr("value"),mediabayar:b("#confForm input[name='mediabayar']:checked").val(),tanggal:b("#tanggal").attr("value"),amount:b("#camount").attr("value"),bankzenius:b("#confForm input[name='bankzenius']:checked").val()}),contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(a){b(".confirmEl").hide();b(".confirmSucceeds").show();b("html, body").animate({scrollTop:b("#confirmSucceeds").offset().top},1E3)}).fail(function(b){}).done(function(){f.attr("value",
"Konfirmasi");a.find(":input:disabled").prop("disabled",!1)})):b("#messageBox").show()})};return a}(znet||{},jQuery,window);
znet=function(a,b,g,h){(a.voucherPurchaseOnlinePage=a.voucherPurchaseOnlinePage||{}).init=function(){b("input#4").click(function(){b(".onetwothree-desc").toggle()});b.fn.serializeObject=function(){var a={};b(this).find('input[type="hidden"], input[type="number"], input[type="text"], input[type="password"], input[type="checkbox"]:checked, input[type="radio"]:checked, select').each(function(){if("hidden"==b(this).attr("type")){var d=b(this).parent().find('input[type="checkbox"][name="'+this.name.replace(/\[/g,
"[").replace(/\]/g,"]")+'"]');if(null!=d&&d.prop("checked"))return}null!==this.name&&this.name!==h&&""!==this.name&&(d=null,d=b(this).is("select")?b(this).find("option:selected").val():this.value,a[this.name]!==h?(a[this.name].push||(a[this.name]=[a[this.name]]),a[this.name].push(d||"")):a[this.name]=d||"")});return a};var a=function(b){return function(){var a=!0,d=0;b(".quantity").each(function(f,g){var h=0,h=b(g).attr("value");0===h.length?h=0:(h=parseInt(h,10),isNaN(h)&&(h=0,a=a&&!1,b(g).addClass("invalidInputEl")));
d+=h});return 0<d&&a}}(jQuery),f=b("#vpurchase"),d=b("#agree");d.click(function(c){b("#vpMsg").hide().empty();c.preventDefault();c=!0;a()||(b("#vpMsg").append("Mohon periksa jumlah voucher Anda"),c=!1);b("input:radio[name='carabayar']").is(":checked")||(c=!1,b("#vpMsg").append("<br>Mohon pilih metode pembayaran"));c?(d.attr("value","Processing.."),f.find(":input:not(:disabled)").prop("disabled",!0),console.log(f.serializeObject()),Q(b.ajax({dataType:"json",type:"POST",data:JSON.stringify(f.serializeObject()),
contentType:"application/json; charset=utf-8",headers:znet.sec.xsrfHeader()})).then(function(b){g.location.href=b["invoice-url"]}).fail(function(a){a=a.responseJSON;for(var c=0,c=0;c<a["err-msgs"].length;c++)b("#vpMsg").append(a["err-msgs"][c]+"<br>");b("#vpMsg").show()}).done(function(){f.find(":input:disabled").prop("disabled",!1);d.attr("value","Beli Sekarang")})):(f.find(":input:disabled").prop("disabled",!1),d.attr("value","Beli Sekarang"),b("#vpMsg").show())})};return a}(znet||{},jQuery,window);
jZnet.video=function(){var a={_player_type:void 0,_player:void 0,_clip:void 0,_vzaar_video_container:"",_flowplayer_flash_param:{src:"",wmode:"opaque",version:[9,15],onFail:function(){document.getElementById("info").innerHTML="You need the latest Flash version to view MP4 movies. Your version is "+this.getVersion()+" You can download here http://get.adobe.com/flashplayer/"}}};a._flowplayer_event=function(a){return{onStart:function(g){$.publish("/j-znet/video/on-play",[a._clip["video-id"]])},onPause:function(g){$.publish("/j-znet/video/on-pause",
[a._clip["video-id"],parseInt(this.getTime())])},onStop:function(g){$.publish("/j-znet/video/on-stop",[a._clip["video-id"],parseInt(this.getTime())])},onFinish:function(g){$.publish("/j-znet/video/on-finish",[a._clip["video-id"]])}}}(a);a._flowplayer_config={debug:!1,key:"#$0ef3073b1d40602b7d6",clip:{onStart:a._flowplayer_event.onStart,onPause:a._flowplayer_event.onPause,onStop:a._flowplayer_event.onStop,onFinish:a._flowplayer_event.onFinish,provider:"rtmp",connectionProvider:"secure"},logo:{top:130,
right:232,opacity:.2,fullscreenOnly:!1,displayTime:5,fadeSpeed:1E3},plugins:{}};a.get_video=function(a,g){$.ajax({dataType:"json",url:a,success:function(a,b,f){a.status="ok";a.reason="ok";g(a)},error:function(a,b,f){a={status:f,video:{},reason:$.trim(a.responseText)};g(a)}})};a.stop=function(){this._player.stop()};a.play=function(){var a,g,h;a=this._player;g=this._clip;h=this._player_type;"flash"===h?a&&(h=a.getClip(),void 0===h?(a.setClip(g["video-path"]),a.play(g["video-path"])):(a.setClip(g["video-path"]),
a.play())):"ios"===h?a&&(a.src=g["ios-video-path"],a.play()):"vzaar"===h&&(this.remove_vzaar_iframe(),this.create_vzaar_iframe(this._vzaar_video_container,g["vzaar-video-id"]))};a.attach_flowplayer=function(b){a._player_type="flash";this._player=b};a._ios_player_pause_event=!0;a.attach_ios_player=function(a){var g=this;a.stop=function(){g._ios_player_pause_event=!1;this.pause();g._ios_player_pause_event=!0};$.subscribe("/j-znet/video/ios/on-stop",function(a,b,f){$.publish("/j-znet/video/on-stop",
[b,f])});$.subscribe("/j-znet/video/ios/on-pause",function(a,b,f){$.publish("/j-znet/video/on-pause",[b,f])});$(a).on("play",function(){var a=g._clip;g._ios_player_pause_event=!0;$.publish("/j-znet/video/on-play",[a["video-id"]])});$(a).on("pause",function(){var a=g._clip;g._ios_player_pause_event?$.publish("/j-znet/video/ios/on-pause",[a["video-id"],parseInt(this.currentTime)]):$.publish("/j-znet/video/ios/on-stop",[a["video-id"],parseInt(this.currentTime)])});$(a).on("ended",function(){$.publish("/j-znet/video/on-finish",
[g._clip["video-id"]])});this._player_type="ios";this._player=a};a.attach_vzaar_player=function(a){var g;g=this;this._player_type="vzaar";this._player={};this._player.stop=function(){$(g._vzaar_video_container+" iframe").remove()}};a.remove_vzaar_iframe=function(){$(this._vzaar_video_container+" iframe").remove()};a.create_vzaar_iframe=function(a,g){var h;this._vzaar_video_container=a;h=$("<iframe>").attr({allowTransparency:"true","class":"vzaar-video-player",frameborder:"0",height:"480",id:"vzvd-"+
g,name:"vzvd-"+g,src:"http://view.vzaar.com/"+g+"/player",title:"vzaar video player",type:"text/html",width:"640"}).prop({allowFullScreen:!0,webkitAllowFullScreen:!0,mozallowfullscreen:!0});$(a).append(h)};a.attach_clip=function(a){this._clip=a};a.init_ga_video_event_tracking=function(){$.subscribe("/j-znet/video/on-play",function(a,g){_gaq.push(["_trackEvent","Videos","Play",g])});$.subscribe("/j-znet/video/on-pause",function(a,g,h){_gaq.push(["_trackEvent","Videos","Pause",g,h])});$.subscribe("/j-znet/video/on-stop",
function(a,g,h){_gaq.push(["_trackEvent","Videos","Stop",g,h])});$.subscribe("/j-znet/video/on-finish",function(a,g){_gaq.push(["_trackEvent","Videos","Finish",g])})};return a}();
